	<div class="titleBar">
		<h1>Routing Rules</h1>
	</div>
	<p>
		The router doesn't has immediate access to all the routing rules. The rules are separated into two types: <strong>Admin</strong>,
		and <strong>Public</strong>. A top-level rule is implemented for handling these two rule groups.
	</p>
	<p>
		This top-level rule grabs all the registered routing rules for a rule-type, selects the rule on the basis of its
		<strong>Route Prefix</strong> and finally calls the <code>match()</code> method on this sub-rule to get a RouteMatch object.
	</p>
	<div class="titleBar">
		<h2>Default Route-Path</h2>
	</div>
	<p>
		<code class="muted">&lt;!-- TODO --&gt;</code>
	</p>
	<div class="titleBar">
		<h2>Admin Routing Rules</h2>
	</div>
	<table width="100%">
		<tr class="muted">
			<td width="40%"><strong>Route Prefix</strong></td>
			<td width="60%"><strong>Associated Class</strong></td>
		</tr>
		<tr>
			<td>add-ons</td>
			<td>XenForo_Route_PrefixAdmin_AddOns</td>
		</tr>
		<tr>
			<td>admin-navigation</td>
			<td>XenForo_Route_PrefixAdmin_AdminNavigation</td>
		</tr>
		<tr>
			<td>admin-permissions</td>
			<td>XenForo_Route_PrefixAdmin_AdminPermissions</td>
		</tr>
		<tr>
			<td>admin-style-properties</td>
			<td>XenForo_Route_PrefixAdmin_AdminStyleProperties</td>
		</tr>
		<tr>
			<td>admin-templates</td>
			<td>XenForo_Route_PrefixAdmin_AdminTemplates</td>
		</tr>
		<tr>
			<td>admins</td>
			<td>XenForo_Route_PrefixAdmin_Admins</td>
		</tr>
		<tr>
			<td>appearance</td>
			<td>XenForo_Route_PrefixAdmin_Appearance</td>
		</tr>
		<tr>
			<td>applications</td>
			<td>XenForo_Route_PrefixAdmin_Applications</td>
		</tr>
		<tr>
			<td>banning</td>
			<td>XenForo_Route_PrefixAdmin_Banning</td>
		</tr>
		<tr>
			<td>bb-code-media-sites</td>
			<td>XenForo_Route_PrefixAdmin_BbCodeMediaSites</td>
		</tr>
		<tr>
			<td>captcha-questions</td>
			<td>XenForo_Route_PrefixAdmin_CaptchaQuestions</td>
		</tr>
		<tr>
			<td>categories</td>
			<td>XenForo_Route_PrefixAdmin_Categories</td>
		</tr>
		<tr>
			<td>code-event-listeners</td>
			<td>XenForo_Route_PrefixAdmin_CodeEventListeners</td>
		</tr>
		<tr>
			<td>code-events</td>
			<td>XenForo_Route_PrefixAdmin_CodeEvents</td>
		</tr>
		<tr>
			<td>cron</td>
			<td>XenForo_Route_PrefixAdmin_Cron</td>
		</tr>
		<tr>
			<td>development</td>
			<td>XenForo_Route_PrefixAdmin_Development</td>
		</tr>
		<tr>
			<td>email-templates</td>
			<td>XenForo_Route_PrefixAdmin_EmailTemplates</td>
		</tr>
		<tr>
			<td>feeds</td>
			<td>XenForo_Route_PrefixAdmin_Feeds</td>
		</tr>
		<tr>
			<td>forums</td>
			<td>XenForo_Route_PrefixAdmin_Forums</td>
		</tr>
		<tr>
			<td>identity-services</td>
			<td>XenForo_Route_PrefixAdmin_IdentityServices</td>
		</tr>
		<tr>
			<td>import</td>
			<td>XenForo_Route_PrefixAdmin_Import</td>
		</tr>
		<tr>
			<td>index</td>
			<td>XenForo_Route_PrefixAdmin_Index</td>
		</tr>
		<tr>
			<td>languages</td>
			<td>XenForo_Route_PrefixAdmin_Languages</td>
		</tr>
		<tr>
			<td>link-forums</td>
			<td>XenForo_Route_PrefixAdmin_LinkForums</td>
		</tr>
		<tr>
			<td>login</td>
			<td>XenForo_Route_PrefixAdmin_Login</td>
		</tr>
		<tr>
			<td>logs</td>
			<td>XenForo_Route_PrefixAdmin_Logs</td>
		</tr>
		<tr>
			<td>moderators</td>
			<td>XenForo_Route_PrefixAdmin_Moderators</td>
		</tr>
		<tr>
			<td>node-permissions</td>
			<td>XenForo_Route_PrefixAdmin_NodePermissions</td>
		</tr>
		<tr>
			<td>nodes</td>
			<td>XenForo_Route_PrefixAdmin_Nodes</td>
		</tr>
		<tr>
			<td>options</td>
			<td>XenForo_Route_PrefixAdmin_Options</td>
		</tr>
		<tr>
			<td>pages</td>
			<td>XenForo_Route_PrefixAdmin_Pages</td>
		</tr>
		<tr>
			<td>permissions</td>
			<td>XenForo_Route_PrefixAdmin_Permissions</td>
		</tr>
		<tr>
			<td>phrases</td>
			<td>XenForo_Route_PrefixAdmin_Phrases</td>
		</tr>
		<tr>
			<td>route-prefixes</td>
			<td>XenForo_Route_PrefixAdmin_RoutePrefixes</td>
		</tr>
		<tr>
			<td>smilies</td>
			<td>XenForo_Route_PrefixAdmin_Smilies</td>
		</tr>
		<tr>
			<td>spam-cleaner</td>
			<td>XenForo_Route_PrefixAdmin_SpamCleaner</td>
		</tr>
		<tr>
			<td>style-properties</td>
			<td>XenForo_Route_PrefixAdmin_StyleProperties</td>
		</tr>
		<tr>
			<td>style-property-defs</td>
			<td>XenForo_Route_PrefixAdmin_StylePropertyDefinitions</td>
		</tr>
		<tr>
			<td>style-property-groups</td>
			<td>XenForo_Route_PrefixAdmin_StylePropertyGroups</td>
		</tr>
		<tr>
			<td>styles</td>
			<td>XenForo_Route_PrefixAdmin_Styles</td>
		</tr>
		<tr>
			<td>system-permissions</td>
			<td>XenForo_Route_PrefixAdmin_SystemPermissions</td>
		</tr>
		<tr>
			<td>templates</td>
			<td>XenForo_Route_PrefixAdmin_Templates</td>
		</tr>
		<tr>
			<td>tools</td>
			<td>XenForo_Route_PrefixAdmin_Tools</td>
		</tr>
		<tr>
			<td>trophies</td>
			<td>XenForo_Route_PrefixAdmin_Trophies</td>
		</tr>
		<tr>
			<td>trophy-user-titles</td>
			<td>XenForo_Route_PrefixAdmin_TrophyUserTitles</td>
		</tr>
		<tr>
			<td>user-group-permissions</td>
			<td>XenForo_Route_PrefixAdmin_UserGroupPermissions</td>
		</tr>
		<tr>
			<td>user-groups</td>
			<td>XenForo_Route_PrefixAdmin_UserGroups</td>
		</tr>
		<tr>
			<td>user-permissions</td>
			<td>XenForo_Route_PrefixAdmin_UserPermissions</td>
		</tr>
		<tr>
			<td>user-upgrades</td>
			<td>XenForo_Route_PrefixAdmin_UserUpgrades</td>
		</tr>
		<tr>
			<td>users</td>
			<td>XenForo_Route_PrefixAdmin_Users</td>
		</tr>
		<tr>
			<td>_css</td>
			<td>XenForo_Route_PrefixAdmin_CssInternal</td>
		</tr>
	</table>
	<div class="titleBar">
		<h2>Public Routing Rules</h2>
	</div>
	<table width="100%">
		<tr class="muted">
			<td width="40%"><strong>Route Prefix</strong></td>
			<td width="60%"><strong>Associated Class</strong></td>
		</tr>
		<tr>
			<td>account</td>
			<td>XenForo_Route_Prefix_Account</td>
		</tr>
		<tr>
			<td>account-confirmation</td>
			<td>XenForo_Route_Prefix_AccountConfirmation</td>
		</tr>
		<tr>
			<td>attachments</td>
			<td>XenForo_Route_Prefix_Attachments</td>
		</tr>
		<tr>
			<td>categories</td>
			<td>XenForo_Route_Prefix_Categories</td>
		</tr>
		<tr>
			<td>conversations</td>
			<td>XenForo_Route_Prefix_Conversations</td>
		</tr>
		<tr>
			<td>editor</td>
			<td>XenForo_Route_Prefix_Editor</td>
		</tr>
		<tr>
			<td>find-new</td>
			<td>XenForo_Route_Prefix_FindNew</td>
		</tr>
		<tr>
			<td>forums</td>
			<td>XenForo_Route_Prefix_Forums</td>
		</tr>
		<tr>
			<td>goto</td>
			<td>XenForo_Route_Prefix_Goto</td>
		</tr>
		<tr>
			<td>help</td>
			<td>XenForo_Route_Prefix_Help</td>
		</tr>
		<tr>
			<td>index</td>
			<td>XenForo_Route_Prefix_Index</td>
		</tr>
		<tr>
			<td>inline-mod</td>
			<td>XenForo_Route_Prefix_InlineMod</td>
		</tr>
		<tr>
			<td>link-forums</td>
			<td>XenForo_Route_Prefix_LinkForums</td>
		</tr>
		<tr>
			<td>login</td>
			<td>XenForo_Route_Prefix_Login</td>
		</tr>
		<tr>
			<td>logout</td>
			<td>XenForo_Route_Prefix_Logout</td>
		</tr>
		<tr>
			<td>lost-password</td>
			<td>XenForo_Route_Prefix_LostPassword</td>
		</tr>
		<tr>
			<td>members</td>
			<td>XenForo_Route_Prefix_Members</td>
		</tr>
		<tr>
			<td>misc</td>
			<td>XenForo_Route_Prefix_Misc</td>
		</tr>
		<tr>
			<td>moderation-queue</td>
			<td>XenForo_Route_Prefix_ModerationQueue</td>
		</tr>
		<tr>
			<td>online</td>
			<td>XenForo_Route_Prefix_Online</td>
		</tr>
		<tr>
			<td>pages</td>
			<td>XenForo_Route_Prefix_Pages</td>
		</tr>
		<tr>
			<td>posts</td>
			<td>XenForo_Route_Prefix_Posts</td>
		</tr>
		<tr>
			<td>profile-posts</td>
			<td>XenForo_Route_Prefix_ProfilePosts</td>
		</tr>
		<tr>
			<td>recent-activity</td>
			<td>XenForo_Route_Prefix_RecentActivity</td>
		</tr>
		<tr>
			<td>register</td>
			<td>XenForo_Route_Prefix_Register</td>
		</tr>
		<tr>
			<td>reports</td>
			<td>XenForo_Route_Prefix_Reports</td>
		</tr>
		<tr>
			<td>search</td>
			<td>XenForo_Route_Prefix_Search</td>
		</tr>
		<tr>
			<td>spam-cleaner</td>
			<td>XenForo_Route_Prefix_SpamCleaner</td>
		</tr>
		<tr>
			<td>threads</td>
			<td>XenForo_Route_Prefix_Threads</td>
		</tr>
		<tr>
			<td>watched</td>
			<td>XenForo_Route_Prefix_Watched</td>
		</tr>
	</table>